### ISSUE TITLE
Computing Routes Failed

### ISSUE THREAD

**Issue by Spuddya7x** [ARBProtocol/solana-jupiter-bot#14]
Sorted the private key issue out, now I am faced with this not able to use the RPC/Jupiter Connection.

![image](https://user-images.githubusercontent.com/48963293/186504375-1bbeb9bb-a66d-4900-b5f0-56ab3f265241.png)
 Im using https://arbprotocol.genesysgo.net as an RPC to test, as youve mentioned it before, yet still failing. Ive also tried the standard Solana Serum RPC to no avail.

**Comment by pmioduszewski** [comment]
Hi! 😄  Sorry to hear that, hope it works now

**Comment by Spuddya7x** [comment]
Hi mate, all sorted. Didn't realize it throws this error if the settings aren't compatible.
