### ISSUE TITLE
No Routes Found 

### ISSUE THREAD

**Issue by UsamaLion** [ARBProtocol/solana-jupiter-bot#16]
![image](https://user-images.githubusercontent.com/62137456/189474444-3f3f5273-53fd-4788-8993-06191925eb04.png)

ERROR: Cannot read properties of undefined 

I have uploaded the image Kindly view the image and help me with this error

**Comment by pmioduszewski** [comment]
Hi, You're probably using `npm` instead of `yarn`. If so, please clone the repo again and use `yarn` to install packages.

**Comment by UsamaLion** [comment]
no I'm using Yarn 
![image](https://user-images.githubusercontent.com/62137456/189476065-f84a9dc9-bd54-40b2-938e-9a8a78945875.png)

**Comment by UsamaLion** [comment]
I'm Using Yarn

**Comment by pmioduszewski** [comment]
Can You share config.json?

**Comment by UsamaLion** [comment]
{
  "network": "mainnet-beta",
  "rpc": [
    "https://arbprotocol.genesysgo.net"
  ],
  "tradingStrategy": "arbitrage",
  "tokenA": {
    "symbol": "USDT",
    "address": "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"
  },
  "tokenB": {
    "symbol": "",
    "address": ""
  },
  "slippage": "profitOrKill",
  "minPercProfit": "1",
  "minInterval": 30,
  "tradeSize": {
    "value": null,
    "strategy": "cumulative"
  },
  "ui": {
    "defaultColor": "cyan"
  },
  "storeFailedTxInHistory": true
}



Here is Config.json file code

**Comment by pmioduszewski** [comment]
`tradeSize.value` shouldn't be null, interesting. Maybe You forgot to set trade size in the wizard?

**Comment by UsamaLion** [comment]
i tried it both way i tried to run with value of 100 USDT but it still give me this error

**Comment by UsamaLion** [comment]
if you are available I can give you access to my pc using any desk software. I will be very grateful for your help

**Comment by pmioduszewski** [comment]
Just try to change `null` to 1 in the `tradeSize.value` and let me know

**Comment by UsamaLion** [comment]
![image](https://user-images.githubusercontent.com/62137456/189477328-6dad2dc1-5015-4cca-98f0-c2ef3cdb6f08.png)
Its still giving the error

**Comment by pmioduszewski** [comment]
Unfortunately, I can't reproduce this issue 🤔 Sorry mate 🤷‍♂️
Make sure the `yarn list --pattern @jup-ag/core` command returns `@jup-ag/core@1.0.0-beta.28`
In the next release, I'll update jup-ag/core to the latest beta version, maybe somehow this will help in your case

**Comment by UsamaLion** [comment]
![image](https://user-images.githubusercontent.com/62137456/189478904-fbc75099-643e-4c98-8231-5b5986c4e54e.png)
its returning this @jup-ag/core@1.0.0-test.35

**Comment by pmioduszewski** [comment]
Ok, that's something. Try this: `yarn add @jup-ag/core@1.0.0-beta.28` and let me know 😄
