### ISSUE TITLE
StructError: Expected the value to satisfy a union of `type | type`, but received: [object Object]

### ISSUE THREAD

**Issue by DeewaTT91** [ARBProtocol/solana-jupiter-bot#57]
This is the error:

> ✖ Setting up failed!
>         Loading Jupiter SDK...
> ERROR: Expected the value to satisfy a union of `type | type`, but received: [object Object]
> StructError: Expected the value to satisfy a union of `type | type`, but received: [object Object]
>     at validate (C:\arb protocol\solana-jupiter-bot-main\node_modules\@solana\web3.js\node_modules\superstruct\lib\index.cjs:363:19)
>     at Object.create (C:\arb protocol\solana-jupiter-bot-main\node_modules\@solana\web3.js\node_modules\superstruct\lib\index.cjs:319:18)
>     at Connection.getTokenAccountsByOwner (C:\arb protocol\solana-jupiter-bot-main\node_modules\@solana\web3.js\lib\index.cjs.js:7304:29)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async vn (C:\arb protocol\solana-jupiter-bot-main\node_modules\@jup-ag\core\dist\core.cjs.production.min.js:1:174517)
>     at async Promise.all (index 2)
>     at async Cn.load (C:\arb protocol\solana-jupiter-bot-main\node_modules\@jup-ag\core\dist\core.cjs.production.min.js:1:187209)
>     at async setup (C:\arb protocol\solana-jupiter-bot-main\src\bot\setup.js:75:19)
>     at async run (C:\arb protocol\solana-jupiter-bot-main\src\bot\index.js:398:39)
>

**Comment by meta-lite** [comment]
same result on my end
