### ISSUE TITLE
Ping Pong trading not working with default RPC

### ISSUE THREAD

**Issue by nicolas-ra** [ARBProtocol/solana-jupiter-bot#69]
I am using the default RPC `https://api.mainnet-beta.solana.com` . 
I get the following error when starting a PIngPong trading 

```
✖ Setting up failed!
        Loading the Jupiter V4 SDK and getting ready to trade...
ERROR: Account info xxx missing
```

I tried with the following other RPCs: 
             https://solana-api.projectserum.com,
             https://rpc.ankr.com/solana,
             https://solana.api.onfinality.io/public,
             https://solana.drpc.org

All of them make the bot exit with an error saying i'm not ARB ready.

**Comment by TestGithub2024m** [comment]
> I am using the default RPC `https://api.mainnet-beta.solana.com` . I get the following error when starting a PIngPong trading
> 
> ```
> ✖ Setting up failed!
>         Loading the Jupiter V4 SDK and getting ready to trade...
> ERROR: Account info xxx missing
> ```
> 
> I tried with the following other RPCs: https://solana-api.projectserum.com, https://rpc.ankr.com/solana, https://solana.api.onfinality.io/public, https://solana.drpc.org
> 
> All of them make the bot exit with an error saying i'm not ARB ready.

TRY https://solana-mainnet.g.alchemy.com/v2/A10IiY2ag0K6JwZfdf4yjcReDud_kl0n

**Comment by TestGithub2024m** [comment]
> I am using the default RPC `https://api.mainnet-beta.solana.com` . I get the following error when starting a PIngPong trading
> 
> ```
> ✖ Setting up failed!
>         Loading the Jupiter V4 SDK and getting ready to trade...
> ERROR: Account info xxx missing
> ```
> 
> I tried with the following other RPCs: https://solana-api.projectserum.com, https://rpc.ankr.com/solana, https://solana.api.onfinality.io/public, https://solana.drpc.org
> 
> All of them make the bot exit with an error saying i'm not ARB ready.

TRY https://solana-mainnet.g.alchemy.com/

**Comment by carpathiansalt** [comment]
hi, I have the same problem, any suggestions please, i'm using the free accounts for testing.

**Comment by fasogbon** [comment]
Me too please

**Comment by alikopasa** [comment]
any solution for that?
