### ISSUE TITLE
No routes found for the input and output mints

### ISSUE THREAD

**Issue by Dinkous** [ARBProtocol/solana-jupiter-bot#70]
I had the bot up and running no issues. I then crtl+c to stop the bot, and the next time I went to restart it I got an error for no found routes for input and output mints. I'll attach a screen grab of the command prompt. 
![Screenshot 2024-03-20 165307](https://github.com/ARBProtocol/solana-jupiter-bot/assets/20568373/477c72b9-a828-46ca-bc21-9698c5ab8492)

**Comment by VertexHate** [comment]
how did you solve this problem?
