### ISSUE TITLE
99% of tx give transaction was not confirmed 

### ISSUE THREAD

**Issue by sellerbtc** [ARBProtocol/solana-jupiter-bot#72]
hello man i think the bot need some update on priority fee it  99.9% give    transaction was not confirmed  thnx in advance

**Comment by sellerbtc** [comment]
i try even with revert back swap   and same error   transaction was not confirmed

**Comment by RaoMusharraf** [comment]
I also facing this issue What is the solution?

**Comment by RaoMusharraf** [comment]
how to confirm the trades
