### ISSUE TITLE
No routes found for the input and output mints

### ISSUE THREAD

**Issue by AlexandreColauto** [ARBProtocol/solana-jupiter-bot#75]
![image](https://github.com/ARBProtocol/solana-jupiter-bot/assets/43041764/1c414f43-99a7-4347-9b51-7ecfdde26d76)

Cant find routes, the same error as some issues open, but they are closed without explaining how they was fixed. 
Here is my config file:

![image](https://github.com/ARBProtocol/solana-jupiter-bot/assets/43041764/a72eb5a8-b96a-4591-9693-969740d93aa7)

**Comment by joeyfigaro** [comment]
This is happening to me also–fresh install, first run. Bot is currently unusable due to this error.

**Comment by machinedramon** [comment]
Same here. Node 18.20.4.
