### ISSUE TITLE
pingpong token to same token

### ISSUE THREAD

**Issue by victordlp8** [ARBProtocol/solana-jupiter-bot#8]
When pingponging USDC to USDC the new current balance that the bot detects its the actual profit, so it displays that it had -99% profit.

**Comment by pmioduszewski** [comment]
It's because Jupiter SDK can't return correct out amounts on TokenA<>TokenA pairs. Don't use the `pingpong` strategy for arbitrage. U can try the `arbitrage strategy (beta)`, it should work fine on USDC<>USDC but U need to have superfast RPC or luck 😉
