### ISSUE TITLE
Slippage error -> Old: Unknown error, visit the explorer

### ISSUE THREAD

**Issue by victordlp8** [ARBProtocol/solana-jupiter-bot#9]
Im trying the arbitrage strategy and it has done 45 fails in a row getting this error, "Unknown error, visit the explorer". What should I do?

Edit: I didnt have enough SOL for a serum order probably. I think that was it. Now there is a lot of slippage errors, is there a way so that I can set the slippage? The script says SLIPPAGE but I dont think thats the same slippage that Jupiter uses.

**Comment by pmioduszewski** [comment]
Hi, these errors are not from the bot but from the Solana network (slippage) or Jupiter/AMM (unknown err...), please check TXs on Solscan. You can also check this comment:
[https://github.com/ARBProtocol/solana-jupiter-bot/issues/3#issuecomment-1179688897](https://github.com/ARBProtocol/solana-jupiter-bot/issues/3#issuecomment-1179688897)

For `Unknown error, visit the explorer` You need to ask on Jupiter Discord.
